### ISSUE TITLE
How about changing the repository name?

### ISSUE THREAD

**Issue by henry-will** [klaytn/sc-vt#2]
**Is your request related to a problem? Please describe.**
The sc-vt name is simple, but I don't know if it is about value transfer and service chain.

**Describe the solution you'd like**
I recommend a service-chain-value-transfer-examples

**Comment by hyunsooda** [comment]
cc. @2dvorak @kjhman21 @nohkwak @hqjang-pepper

**Comment by nohkwak** [comment]
The "service-chain-value-transfer-examples" repo name seems fine.
There is an existing "service-chain-deploy" repo, so it would be good to maintain service-chain- as a prefix in the future.

**Comment by baerae-colin** [comment]
But didn't we decide that we will use "ServiceChain"? Then the prefix "servicechain" is more appropriate for me.
What about "servicechain-value-transfer-examples"? :)

**Comment by nohkwak** [comment]
Godd ^^
I don't think there is a better suggestion than this.

2022년 3월 16일 (수) 오전 1:39, Junghyun Colin Kim ***@***.***>님이
작성:

**Comment by hqjang-pepper** [comment]
Agree with @kjhman21's option :)

**Comment by henry-will** [comment]
So, how about changing service-chain-deploy to servicechain-deploy?

**Comment by henry-will** [comment]
@hyunsooda @2dvorak 

I will change repo names as follows.
- [x] sv-vt -> servicechain-value-transfer-examples @hyunsooda 
- [x] service-chain-deploy -> servicechain-deploy @2dvorak
