### ISSUE TITLE
Need to support HA configured bridge

### ISSUE THREAD

**Issue by 2dvorak** [klaytn/sc-vt#5]
The current design assumes that there is only one bridge.

To support HA in value transfer example, it needs to:
1. Call `registerOperator` for additional operators
2. Call `subbridge` JSON RPCs (i.e., registerBridge, subscribeBridge, registerToken) for additional bridges

To do that, we need 1) child node URL for the JSON RPC endpoint and 2) operator address for additional bridges.

The simplest way to make such information available is to refactor `bridge_info.json` to provide list of bridges, like:
```
{
    "child" : {
        "urls": ["http://127.0.0.1:8551"],
        "key": "0xc544b44c1c58955af516c1f2ff17f8fd522604f1ea6b64db79e067343ed5e307",
        "operators": ["0x7920de6f6d9d1e9fe2e35b48ab8cfce545673888"]
    },
    "parent" : {
        "urls": ["http://127.0.0.1:9781"],
        "key": "0x4b07ca7412ad2bb0e62db30369b9f08a8724fb81fce4b3b1af23800233074fbf",
        "operators": ["0xa36a4d6d15fa692eceaa616008bc2decc5c0403b"]
    }
}
```
However, it hides the binding between the URL and operator address.

There are other options, like:
```
{
    "child" : {
        "key": "0xc544b44c1c58955af516c1f2ff17f8fd522604f1ea6b64db79e067343ed5e307",
        "bridges": [
          {
            "urls": "http://127.0.0.1:8551",
            "operators": "0xaaaa"
          },
          {
            "urls": "http://127.0.0.1:8552",
            "operators": "0xbbbb"
          }
        ]
    },
    "parent" : {
        "key": "0x4b07ca7412ad2bb0e62db30369b9f08a8724fb81fce4b3b1af23800233074fbf",
        "bridges": [
          {
            "urls": "http://127.0.0.1:8553",
            "operators": "0xcccc"
          },
          {
            "urls": "http://127.0.0.1:8554",
            "operators": "0xdddd"

          }
        ]
    }
}
```
Or we can make multiple `bridge_info.json` files like `bridge_info_0.json`, `bridge_info_1.json`. Since we do not need multiple keys for the child and parent chain, that field might be duplicated across multiple `bridge_info_x.json` files.

The first option requires minimum change to the existing code, so I created a sample PR with that option in #4.

**Comment by baerae-colin** [comment]
second option looks good to me, but we also think about
1. key is a plain text
2. What actually 'key' means. It needs to be updated like "sender" or something more meaningful one.

**Comment by 2dvorak** [comment]
@kjhman21 Thank you for the feedback. During the ServiceChain meeting, there were feedback that the binding between child bridges and parent bridges are still hidden. So the following struct was discussed:
```
{
  "key" : {
    "child": "0xc544b44c1c58955af516c1f2ff17f8fd522604f1ea6b64db79e067343ed5e307",
    "parent": "0x4b07ca7412ad2bb0e62db30369b9f08a8724fb81fce4b3b1af23800233074fbf"
  }
  "bridges": [
    {
      "child": {
        "url": "http://127.0.0.1:8551",
        "operator": "0xaaaa"
      },
      "parent": {
        "url": "http://127.0.0.1:8552",
        "operator": "0xbbbb"
      }
    },
    {
      "child": {
        "url": "http://127.0.0.1:8553",
        "operator": "0xcccc"
      },
      "parent": {
        "url": "http://127.0.0.1:8554",
        "operator": "0xdddd"
      }
    },
  ]
}
```

Please take another look.

**Comment by 2dvorak** [comment]
> second option looks good to me, but we also think about
> 
> 1. key is a plain text
> 2. What actually 'key' means. It needs to be updated like "sender" or something more meaningful one.

1. I think using plaintext key for test purpose is inevitable. Maybe we can explicitly show the user that those keys are just test purpose like [this code](https://github.com/klaytn/servicechain-value-transfer-examples/blob/master/hardhat/hardhat.config.js#L135)?
2. I'll update it to `sender`. Or the above link uses `account`, which one do you think is better?

BTW, I'll make another PR to `klaytn-deploy` to update `scconf` command to use newer structure of `bridge_info.json`

**Comment by baerae-colin** [comment]
> > second option looks good to me, but we also think about
> > 
> > 1. key is a plain text
> > 2. What actually 'key' means. It needs to be updated like "sender" or something more meaningful one.
> 
> 1. I think using plaintext key for test purpose is inevitable. Maybe we can explicitly show the user that those keys are just test purpose like [this code](https://github.com/klaytn/servicechain-value-transfer-examples/blob/master/hardhat/hardhat.config.js#L135)?
> 2. I'll update it to `sender`. Or the above link uses `account`, which one do you think is better?
> 
> BTW, I'll make another PR to `klaytn-deploy` to update `scconf` command to use newer structure of `bridge_info.json`

1. Hmm, yeah. that could be one solution. I have no strict opinion that we need to solve this. I was just wondering what we can do better or not.
2. Please discuss with ServiceChain members to find a word that represents the meaning well. :)

**Comment by henry-will** [comment]
> 2. I'll update it to sender. Or the above link uses account, which one do you think is better?

2. If child and parent don't have the opposite direction, I like sender more than account.

**Comment by hyunsooda** [comment]
Sorry for the late response.

1. I have no idea why you grouped `operator` and `url`? The `url` is just an IP address for the caver connection. There's no correlation between `url` and `operator`. Could you clarify it if I'm missing something?
2. The ambiguous name of the `key` was already mentioned and your suggested name sounds good.
3. Renaming `operator` to `operator_address` seems more apparent to erase confusion about its meaning.  
4. Do you think it is kindly to describe the role of each property in the configuration file to the README? The `json` does not allow comments in the file. It seems my fault to choose json format at the initial push.

**Comment by 2dvorak** [comment]
> Sorry for the late response.
> 
> 1. I have no idea why you grouped `operator` and `url`? The `url` is just an IP address for the caver connection. There's no correlation between `url` and `operator`. Could you clarify it if I'm missing something?
> 2. The ambiguous name of the `key` was already mentioned and your suggested name sounds good.
> 3. Renaming `operator` to `operator_address` seems more apparent to erase confusion about its meaning.
> 4. Do you think it is kindly to describe the role of each property in the configuration file to the README? The `json` does not allow comments in the file. It seems my fault to choose json format at the initial push.

@hyunsooda Sorry too for the late reply, I missed your comment. Although most questions may be already resolved, I'll answer anyway.
1. The `url` and `operator` are bound to each other because a node has only one URL and only one operator. For example, a child node with a URL of `http://1.2.3.4:8551` would have only one `childOperator` address.
2. Going to use `sender`, but for more details see #6.
3. That sounds good, however `subbridge` API uses `parentOperator` and `childOperator`.. I hope it would be OK to sync with the API names.
4. I do think the README should provide explanation. I'll update the README in my PR. The value transfer example originally used JSON so it's not your fault!!

**Comment by 2dvorak** [comment]
@hyunsooda Also, I tried to remove `operator` and make the deploy script to get operator address itself using the `subbridge` API. However the `subbridge_parentOperator` and `subbridge_childOperator` APIs were not callable via HTTP. They can be only used in the javascript console. cc @henry-will
